name: gromuse
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  collection: ^1.18.0
  dartz: ^0.10.1
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.2.2
  injectable: ^2.3.5
  json_annotation: ^4.9.0
  phosphor_flutter: ^2.0.1
  supabase_flutter: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.4.2
  go_router_builder: ^2.4.1
  envied_generator: ^0.5.4+1
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter_gen:
  output: lib/common/assets/

flutter_native_splash:
  color: "#FCE0A1"
  color_dark: "#064C4F"

  android_12:
    color: "#FCE0A1"
    color_dark: "#064C4F"
    image: assets/images/splash_logo_light.png
    image_dark: assets/images/splash_logo_dark.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeueBold.ttf
        - asset: assets/fonts/HelveticaNeueLight.ttf
        - asset: assets/fonts/HelveticaNeueMedium.ttf
 