name: gromuse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.2
  injectable: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.4.2
  go_router_builder: ^2.4.1

flutter:
  uses-material-design: true
